export const colors = {
  primary: '#007AFF',
  'primary-light': '#4DA6FF',
  'primary-dark': '#0051D5',
  secondary: '#FF6B6B',
  accent: '#4ECDC4',
  success: '#51CF66',
  warning: '#FFD93D',
  error: '#FF5252',
  background: '#F8F9FA',
  'card-background': '#FFFFFF',
  text: '#1A1A1A',
  'text-secondary': '#6B7280',
  'text-on-primary': '#FFFFFF',
} as const;
